annotations:
  category: MachineLearning
  licenses: Apache-2.0
apiVersion: v2
appVersion: "1.0"
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.29.0
  - name: redis-cluster
    repository: https://charts.bitnami.com/bitnami
    alias: redis
    condition: redis.enabled
    version: 11.4.0
description: Helm chart for dial core
home: https://epam-rail.com
icon: "https://docs.dialx.ai/img/favicon.ico"
keywords:
  - ai-dial
kubeVersion: ">=1.23.0-0"
maintainers:
  - name: EPAM Systems
    url: https://github.com/epam
name: dial-core
sources:
  - https://github.com/epam/ai-dial-helm/tree/main/charts/dial-core
version: 4.3.1
