core:
  enabled: true
  serviceAccount:
    create: true
    # -- You can use a aidial.storage.identity/aidial.storage.credential in the environment variable instead.
    annotations:
      eks.amazonaws.com/role-arn: "%%AWS_CORE_ROLE_ARN%%"
  podAnnotations:
    # -- Annotation hack to restart core pod after each Helm chart upgrade
    autorestart: '{{ dateInZone "2006-01-02 15:04:05Z" (now) "UTC" }}'
  configuration:
    encryption:
      secret: "%%CORE_ENCRYPT_SECRET%%"
      key: "%%CORE_ENCRYPT_KEY%%"
  env:
    aidial.config.files: '["/mnt/secrets-store/aidial.config.json"]'
    aidial.storage.provider: "aws-s3"
    aidial.storage.bucket: "%%AWS_CORE_S3_BUCKET_NAME%%"
    aidial.storage.createBucket: "false"
    aidial.storage.prefix: "core"
    aidial.identityProviders.fake.jwksUrl: "http://fakeJwksUrl"
    aidial.identityProviders.fake.rolePath: "roles"
    aidial.identityProviders.fake.issuerPattern: "issuer"
  secrets:
    aidial.config.json: |
      {
        "models": {
          "anthropic.claude-v1": {
            "type": "chat",
            "displayName": "Anthropic (Claude)",
            "iconUrl": "anthropic.svg",
            "endpoint": "http://dial-bedrock.%%NAMESPACE%%.svc.cluster.local/openai/deployments/anthropic.claude-instant-v1/chat/completions"
          }
        },
        "keys": {
          "%%DIAL_API_KEY%%": {
            "role": "chat",
            "project": "example"
          }
        },
        "roles": {
          "chat": {
            "limits": {
              "anthropic.claude-v1": {}
            }
          }
        }
      }
  extraVolumes:
    - name: config
      secret:
        secretName: '{{ template "dialCore.names.fullname" . }}'
        items:
          - key: aidial.config.json
            path: aidial.config.json
  extraVolumeMounts:
    - name: config
      mountPath: "/mnt/secrets-store/aidial.config.json"
      subPath: aidial.config.json
      readOnly: true
  redis:
    enabled: true
    password: "%%REDIS_PASSWORD%%"
  ingress:
    enabled: false

chat:
  enabled: true
  env:
    # -- Canonical URL of your site
    # ref: https://next-auth.js.org/configuration/options#nextauth_url
    NEXTAUTH_URL: "https://chat.%%DOMAIN%%"
    # -- DIAL core API endpoint
    # Internal service name (DNS name) of DIAL core service
    DIAL_API_HOST: "http://dial-core.%%NAMESPACE%%.svc.cluster.local"
    # -- List of DIAL chat features to enable;
    # ref: https://github.com/epam/ai-dial-chat/blob/development/libs/shared/src/types/features.ts
    ENABLED_FEATURES: "conversations-section,prompts-section,top-settings,top-clear-conversation,top-chat-info,top-chat-model-settings,empty-chat-settings,header,footer,likes,conversations-sharing,prompts-sharing,input-files,attachments-manager,conversations-publishing,prompts-publishing"
    # -- External URL of DIAL themes;
    # Same allowlist as for DIAL chat should be applied
    THEMES_CONFIG_HOST: "http://dial-themes.%%NAMESPACE%%.svc.cluster.local"
  secrets:
    NEXTAUTH_SECRET: "%%NEXTAUTH_SECRET%%"
    # -- API key defined in core configuration
    DIAL_API_KEY: "%%DIAL_API_KEY%%"
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/healthcheck-path: /api/health
      alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=86400
      alb.ingress.kubernetes.io/load-balancer-attributes: routing.http2.enabled=true
      alb.ingress.kubernetes.io/listen-ports: '[{ "HTTP" : 80, "HTTPS" : 443 }]'
      alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-TLS-1-2-Ext-2018-06"
      alb.ingress.kubernetes.io/certificate-arn: "%%AWS_CERTIFICATE_ARN%%"
      alb.ingress.kubernetes.io/ssl-redirect: "443"
    hosts:
      - chat.%%DOMAIN%%

themes:
  enabled: true
  ingress:
    enabled: false

bedrock:
  enabled: true

  serviceAccount:
    create: true
    # -- You can use a AWS_ACCESS_KEY/AWS_SECRET_KEY in the environment variable instead.
    annotations:
      eks.amazonaws.com/role-arn: "%%AWS_BEDROCK_ROLE_ARN%%"

  env:
    DIAL_URL: "http://dial-core.%%NAMESPACE%%.svc.cluster.local"
    DEFAULT_REGION: "%%AWS_BEDROCK_REGION%%"
