annotations:
  category: MachineLearning
  licenses: Apache-2.0
apiVersion: v2
appVersion: "0.4.0"
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.31.1
  - name: dial-extension
    version: 1.3.3
    repository: https://charts.epam-rail.com
    alias: frontend
    condition: frontend.enabled
  - name: postgresql
    version: 16.7.12
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
description: Helm chart for DIAL Admin
home: https://dialx.ai
icon: "https://docs.dialx.ai/img/favicon.ico"
keywords:
  - ai-dial
  - ai-dial-admin
kubeVersion: ">=1.25.0-0"
maintainers:
  - name: EPAM Systems
    url: https://github.com/epam
name: dial-admin
sources:
  - https://github.com/epam/ai-dial-helm/tree/main/charts/dial-admin
version: 0.4.4
