{{- if and .Values.valkey.auth.enabled (not .Values.valkey.auth.usersExistingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "valkey.fullname" . }}-auth
  namespace: {{ include "common.names.namespace" . | quote }}
type: Opaque
data:
  {{- range $user, $userData := .Values.valkey.auth.aclUsers }}
  {{ $userData.passwordKey | default $user }}: {{ $userData.password | default (randAlphaNum 16) | b64enc }}
  {{- end }}
{{- end }}