{{- if and .Values.manager.enabled .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.tplvalues.render" (dict "value" .Values.manager.extraEnvVarsSecret "context" .Subcharts.manager) }}
  namespace: {{ include "common.names.namespace" .Subcharts.manager | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.manager.commonLabels "context" $.Subcharts.manager ) | nindent 4 }}
  {{- if .Values.manager.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.manager.commonAnnotations "context" $.Subcharts.manager ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  DATASOURCE_VENDOR: {{ "POSTGRES" | b64enc | quote }}
  POSTGRES_HOST: {{ include "dialAdmin.postgresql.fullname" . | b64enc | quote }}
  POSTGRES_PORT: {{ .Values.postgresql.primary.service.ports.postgresql | b64enc | quote }}
  POSTGRES_DATABASE: {{ .Values.manager.configuration.database.name | b64enc | quote }}
  POSTGRES_DATASOURCE_USERNAME: {{ .Values.manager.configuration.database.user | b64enc | quote }}
  POSTGRES_DATASOURCE_PASSWORD: {{ .Values.manager.configuration.database.password | b64enc | quote }}
{{- end }}
