{{- $postgresManagerPassword := ternary (randAlphaNum 20) .Values.manager.configuration.database.password (empty .Values.manager.configuration.database.password) -}}
{{- if and .Values.manager.enabled .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "manager.database.secretname" . }}
  namespace: {{ include "common.names.namespace" .Subcharts.manager | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.manager.commonLabels "context" $.Subcharts.manager) | nindent 4 }}
  {{- if .Values.manager.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.manager.commonAnnotations "context" $.Subcharts.manager) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  DATASOURCE_VENDOR: {{ "POSTGRES" | b64enc | quote }}
  POSTGRES_HOST: {{ include "dialAdmin.postgresql.fullname" . | b64enc | quote }}
  POSTGRES_PORT: {{ .Values.postgresql.primary.service.ports.postgresql | b64enc | quote }}
  POSTGRES_DATABASE: {{ .Values.manager.configuration.database.name | b64enc | quote }}
  POSTGRES_DATASOURCE_USERNAME: {{ .Values.manager.configuration.database.user | b64enc | quote }}
  POSTGRES_DATASOURCE_PASSWORD: {{ $postgresManagerPassword | b64enc | quote }}
---
{{- end }}
{{- if .Values.postgresql.enabled }}
{{- $database := .Values.manager.configuration.database.name }}
{{- $user := .Values.manager.configuration.database.user }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.tplvalues.render" (dict "value" .Values.postgresql.primary.initdb.scriptsSecret "context" $.Subcharts.postgresql) }}
  namespace: {{ include "common.names.namespace" .Subcharts.postgresql | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.postgresql.commonLabels "context" $.Subcharts.postgresql) | nindent 4 }}
  {{- if .Values.postgresql.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.postgresql.commonAnnotations "context" $.Subcharts.postgresql) | nindent 4 }}
  {{- end }}
type: Opaque
{{- if .Values.manager.enabled }}
stringData:
  create-multiple-dbs.sh: |
    #!/bin/bash
    set -e
    echo "Creating multiple databases..."
    echo "Creating database: {{ $database }} with user: {{ $user }}"
    PGPASSWORD="${POSTGRES_POSTGRES_PASSWORD}" psql -v ON_ERROR_STOP=1 --username "postgres" <<-EOSQL
      CREATE USER {{ $user }} WITH ENCRYPTED PASSWORD '{{ $postgresManagerPassword }}';
      CREATE DATABASE {{ $database }} WITH OWNER {{ $user }};
    EOSQL
    echo "{{ $database }} database created."
{{- else }}
stringData: {}
{{- end }}
{{- end }}