{{- if and .Values.deploymentManager.enabled .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.tplvalues.render" (dict "value" .Values.deploymentManager.extraEnvVarsSecret "context" .Subcharts.deploymentManager) }}
  namespace: {{ include "common.names.namespace" .Subcharts.deploymentManager | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.deploymentManager.commonLabels "context" $.Subcharts.deploymentManager ) | nindent 4 }}
  {{- if .Values.deploymentManager.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.deploymentManager.commonAnnotations "context" $.Subcharts.deploymentManager ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  DATASOURCE_VENDOR: {{ "POSTGRES" | b64enc | quote }}
  POSTGRES_HOST: {{ include "dialAdmin.postgresql.fullname" . | b64enc | quote }}
  POSTGRES_PORT: {{ .Values.postgresql.primary.service.ports.postgresql | b64enc | quote }}
  POSTGRES_DATABASE: {{ .Values.deploymentManager.configuration.datasource.name | b64enc | quote }}
  POSTGRES_DATASOURCE_USERNAME: {{ .Values.deploymentManager.configuration.datasource.user | b64enc | quote }}
  POSTGRES_DATASOURCE_PASSWORD: {{ .Values.deploymentManager.configuration.datasource.password | b64enc | quote }}
{{- end }}
