{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.tplvalues.render" (dict "value" .Values.postgresql.primary.initdb.scriptsSecret "context" .Subcharts.postgresql) }}
  namespace: {{ include "common.names.namespace" .Subcharts.postgresql | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.postgresql.commonLabels "context" $.Subcharts.postgresql ) | nindent 4 }}
  {{- if .Values.postgresql.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.postgresql.commonAnnotations "context" $.Subcharts.postgresql ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  create-multiple-dbs.sh: |
    #!/bin/bash
    set -e

    DEPLOYMENT_MANAGER_DATABASE="{{ .Values.deploymentManager.configuration.datasource.database }}"
    DEPLOYMENT_MANAGER_USER="{{ .Values.deploymentManager.configuration.datasource.user }}"
    DEPLOYMENT_MANAGER_PASSWORD="{{ .Values.deploymentManager.configuration.datasource.password }}"

    echo "Creating multiple databases..."

    # Check if any of the required environment variables are empty
    if [ -z "$DEPLOYMENT_MANAGER_DATABASE" ] || [ -z "$DEPLOYMENT_MANAGER_USER" ] || [ -z "$DEPLOYMENT_MANAGER_PASSWORD" ]; then
      echo "Skipping database creation due to missing environment variables."
    else
      echo "Creating database: "$DEPLOYMENT_MANAGER_DATABASE" with user: "$DEPLOYMENT_MANAGER_USER" "
      PGPASSWORD="${POSTGRES_POSTGRES_PASSWORD}" psql -v ON_ERROR_STOP=1 --username "postgres" <<-EOSQL
        CREATE USER $DEPLOYMENT_MANAGER_USER WITH ENCRYPTED PASSWORD '$DEPLOYMENT_MANAGER_PASSWORD';
        CREATE DATABASE $DEPLOYMENT_MANAGER_DATABASE WITH OWNER $DEPLOYMENT_MANAGER_USER;
    EOSQL
    fi
    echo "Multiple databases created."
{{- end }}
