{{- if .Values.postgresql.enabled }}
{{- $database := .Values.deploymentManager.configuration.datasource.name }}
{{- $user := .Values.deploymentManager.configuration.datasource.user }}
{{- $password := .Values.deploymentManager.configuration.datasource.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.tplvalues.render" (dict "value" .Values.postgresql.primary.initdb.scriptsSecret "context" .Subcharts.postgresql) }}
  namespace: {{ include "common.names.namespace" .Subcharts.postgresql | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.postgresql.commonLabels "context" $.Subcharts.postgresql ) | nindent 4 }}
  {{- if .Values.postgresql.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.postgresql.commonAnnotations "context" $.Subcharts.postgresql ) | nindent 4 }}
  {{- end }}
type: Opaque
{{- if and $database $user $password }}
stringData:
  create-multiple-dbs.sh: |
    #!/bin/bash
    set -e
    echo "Creating multiple databases..."
    echo "Creating database: {{ $database }} with user: {{ $user }}"
    PGPASSWORD="${POSTGRES_POSTGRES_PASSWORD}" psql -v ON_ERROR_STOP=1 --username "postgres" <<-EOSQL
      CREATE USER {{ $user }} WITH ENCRYPTED PASSWORD '{{ $password }}';
      CREATE DATABASE {{ $database }} WITH OWNER {{ $user }};
    EOSQL
    echo "{{ $database }} database created."
{{- else }}
stringData: {}
{{- end }}
{{- end }}
