{{- if and .Values.deploymentManager.enabled .Values.deploymentManager.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
{{- if eq (include "common.names.namespace" .Subcharts.deploymentManager) .Values.deploymentManager.configuration.build.namespace }}
kind: Role
{{- else }}
kind: ClusterRole
{{- end }}
metadata:
  name: {{ include "common.names.fullname.namespace" .Subcharts.deploymentManager }}
  {{- if eq (include "common.names.namespace" .Subcharts.deploymentManager) .Values.deploymentManager.configuration.build.namespace }}
  namespace: {{ include "common.names.namespace" .Subcharts.deploymentManager | quote }}
  {{- end }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.deploymentManager.commonLabels "context" $.Subcharts.deploymentManager ) | nindent 4 }}
  {{- if .Values.deploymentManager.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.deploymentManager.commonAnnotations "context" $.Subcharts.deploymentManager ) | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - "batch"
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "common.names.fullname.namespace" .Subcharts.deploymentManager }}
  {{- if eq (include "common.names.namespace" .Subcharts.deploymentManager) .Values.deploymentManager.configuration.build.namespace }}
  namespace: {{ include "common.names.namespace" .Subcharts.deploymentManager | quote }}
  {{- end }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.deploymentManager.commonLabels "context" $.Subcharts.deploymentManager ) | nindent 4 }}
  {{- if .Values.deploymentManager.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.deploymentManager.commonAnnotations "context" $.Subcharts.deploymentManager ) | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name:  {{ include "dialAdmin.deploymentManager.serviceAccountName" . }}
    namespace: {{ include "common.names.namespace" . | quote }}
roleRef:
  {{- if eq (include "common.names.namespace" .Subcharts.deploymentManager) .Values.deploymentManager.configuration.build.namespace }}
  kind: Role
  {{- else }}
  kind: ClusterRole
  {{- end }}
  name: {{ include "common.names.fullname.namespace" .Subcharts.deploymentManager }}
  apiGroup: rbac.authorization.k8s.io
{{- if .Values.deploymentManager.configuration.deploy.knative.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
{{- if eq (include "common.names.namespace" .Subcharts.deploymentManager) .Values.deploymentManager.configuration.deploy.knative.namespace }}
kind: Role
{{- else }}
kind: ClusterRole
{{- end }}
metadata:
  name: {{ include "common.names.fullname.namespace" .Subcharts.deploymentManager }}-knative
  {{- if eq (include "common.names.namespace" .Subcharts.deploymentManager) .Values.deploymentManager.configuration.deploy.knative.namespace }}
  namespace: {{ include "common.names.namespace" .Subcharts.deploymentManager | quote }}
  {{- end }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.deploymentManager.commonLabels "context" $.Subcharts.deploymentManager ) | nindent 4 }}
  {{- if .Values.deploymentManager.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.deploymentManager.commonAnnotations "context" $.Subcharts.deploymentManager ) | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - "serving.knative.dev"
    resources:
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - events
    verbs:
      - get
      - list
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "common.names.fullname.namespace" .Subcharts.deploymentManager }}-knative
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.deploymentManager.commonLabels "context" $.Subcharts.deploymentManager ) | nindent 4 }}
  {{- if .Values.deploymentManager.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.deploymentManager.commonAnnotations "context" $.Subcharts.deploymentManager ) | nindent 4 }}
  {{- end }}
  {{- if eq (include "common.names.namespace" .Subcharts.deploymentManager) .Values.deploymentManager.configuration.deploy.knative.namespace }}
  namespace: {{ include "common.names.namespace" .Subcharts.deploymentManager | quote }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name:  {{ include "dialAdmin.deploymentManager.serviceAccountName" . }}
    namespace: {{ include "common.names.namespace" . | quote }}
roleRef:
  {{- if eq (include "common.names.namespace" .Subcharts.deploymentManager) .Values.deploymentManager.configuration.deploy.knative.namespace }}
  kind: Role
  {{- else }}
  kind: ClusterRole
  {{- end }}
  name: {{ include "common.names.fullname.namespace" .Subcharts.deploymentManager }}-knative
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- if .Values.deploymentManager.configuration.deploy.nim.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
{{- if eq (include "common.names.namespace" .Subcharts.deploymentManager) .Values.deploymentManager.configuration.deploy.nim.namespace }}
kind: Role
{{- else }}
kind: ClusterRole
{{- end }}
metadata:
  name: {{ include "common.names.fullname.namespace" .Subcharts.deploymentManager }}-nim
  {{- if eq (include "common.names.namespace" .Subcharts.deploymentManager) .Values.deploymentManager.configuration.deploy.nim.namespace }}
  namespace: {{ include "common.names.namespace" .Subcharts.deploymentManager | quote }}
  {{- end }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.deploymentManager.commonLabels "context" $.Subcharts.deploymentManager ) | nindent 4 }}
  {{- if .Values.deploymentManager.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.deploymentManager.commonAnnotations "context" $.Subcharts.deploymentManager ) | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - "apps.nvidia.com"
    resources:
      - nimservices
    verbs:
      - get
      - list
      - watch
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - events
    verbs:
      - get
      - list
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "common.names.fullname.namespace" .Subcharts.deploymentManager }}-nim
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.deploymentManager.commonLabels "context" $.Subcharts.deploymentManager ) | nindent 4 }}
  {{- if .Values.deploymentManager.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.deploymentManager.commonAnnotations "context" $.Subcharts.deploymentManager ) | nindent 4 }}
  {{- end }}
  {{- if eq (include "common.names.namespace" .Subcharts.deploymentManager) .Values.deploymentManager.configuration.deploy.nim.namespace }}
  namespace: {{ include "common.names.namespace" .Subcharts.deploymentManager | quote }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name:  {{ include "dialAdmin.deploymentManager.serviceAccountName" . }}
    namespace: {{ include "common.names.namespace" . | quote }}
roleRef:
  {{- if eq (include "common.names.namespace" .Subcharts.deploymentManager) .Values.deploymentManager.configuration.deploy.nim.namespace }}
  kind: Role
  {{- else }}
  kind: ClusterRole
  {{- end }}
  name: {{ include "common.names.fullname.namespace" .Subcharts.deploymentManager }}-nim
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- if .Values.deploymentManager.configuration.deploy.kserve.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
{{- if eq (include "common.names.namespace" .Subcharts.deploymentManager) .Values.deploymentManager.configuration.deploy.kserve.namespace }}
kind: Role
{{- else }}
kind: ClusterRole
{{- end }}
metadata:
  name: {{ include "common.names.fullname.namespace" .Subcharts.deploymentManager }}-kserve
  {{- if eq (include "common.names.namespace" .Subcharts.deploymentManager) .Values.deploymentManager.configuration.deploy.kserve.namespace }}
  namespace: {{ include "common.names.namespace" .Subcharts.deploymentManager | quote }}
  {{- end }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.deploymentManager.commonLabels "context" $.Subcharts.deploymentManager ) | nindent 4 }}
  {{- if .Values.deploymentManager.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.deploymentManager.commonAnnotations "context" $.Subcharts.deploymentManager ) | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - "serving.kserve.io"
    resources:
      - inferenceservices
    verbs:
      - get
      - list
      - watch
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - events
    verbs:
      - get
      - list
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "common.names.fullname.namespace" .Subcharts.deploymentManager }}-kserve
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.deploymentManager.commonLabels "context" $.Subcharts.deploymentManager ) | nindent 4 }}
  {{- if .Values.deploymentManager.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.deploymentManager.commonAnnotations "context" $.Subcharts.deploymentManager ) | nindent 4 }}
  {{- end }}
  {{- if eq (include "common.names.namespace" .Subcharts.deploymentManager) .Values.deploymentManager.configuration.deploy.kserve.namespace }}
  namespace: {{ include "common.names.namespace" .Subcharts.deploymentManager | quote }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name:  {{ include "dialAdmin.deploymentManager.serviceAccountName" . }}
    namespace: {{ include "common.names.namespace" . | quote }}
roleRef:
  {{- if eq (include "common.names.namespace" .Subcharts.deploymentManager) .Values.deploymentManager.configuration.deploy.kserve.namespace }}
  kind: Role
  {{- else }}
  kind: ClusterRole
  {{- end }}
  name: {{ include "common.names.fullname.namespace" .Subcharts.deploymentManager }}-kserve
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
